sources:
  - repo: action-hero/rubocop
    sync:
      - ".github/workflows/*.yml"
  - repo: rom-rb/devtools
    sync:
      - "shared/*:${{file}}"
      - "shared/spec/support/*:spec/support/${{name}}.${{ext}}"
      - "templates/*.erb:${{name}}"
