jobs:
  tests:
    services:
      db:
        image: postgres:10.8
        env:
          POSTGRES_USER: runner
          POSTGRES_PASSWORD: ""
          POSTGRES_DB: rom_factory
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    strategy:
      matrix:
        faker:
          - faker-2
        include:
          - ruby: "2.7"
            faker: faker-1
          - ruby: "3.0"
            faker: faker-2
            coverage: "true"
          - ruby: jruby
            database_url: jdbc:postgresql://localhost/rom_factory
    env:
      FAKER: ${{matrix.faker}}
      APT_DEPS: "libpq-dev libmysqlclient-dev libsqlite3-dev"
